name: Test

on: [push, pull_request]

jobs:
  rust:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install FFTW and GSL
      run: |
        sudo apt-get update
        sudo apt-get install libfftw3-dev libgsl-dev
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --workspace --all-targets --exclude python/light-curve
    - name: Build light-curve-feature gsl+fftw-source
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --manifest-path=light-curve-feature/Cargo.toml --all-targets --no-default-features --features gsl,fftw-source
    - name: Build light-curve-feature gsl+fftw-system
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --manifest-path=light-curve-feature/Cargo.toml --all-targets --no-default-features --features gsl,fftw-system
    - name: Build light-curve-feature gsl+fftw-mkl
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --manifest-path=light-curve-feature/Cargo.toml --all-targets --no-default-features --features gsl,fftw-mkl
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --workspace --exclude python/light-curve
    - name: Check formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - name: Run code analysis
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --workspace --exclude python/light-curve --all-targets -- -D warnings


  python:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: python/light-curve

    steps:
    - uses: actions/checkout@v2
    - name: Install FFTW
      run: |
        sudo apt-get update
        sudo apt-get install libfftw3-dev
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install maturin, tox and black
      run: pip install maturin tox black
    - name: Build package with static FFTW
      run: maturin build
    - name: Build package with dynamic FFTW
      run: maturin build --manylinux=off --cargo-extra-args="--no-default-features --features fftw-dynamic,nonlinear-fit"
    - name: Build package with dynamic MKL
      run: maturin build --manylinux=off --cargo-extra-args="--no-default-features --features mkl,nonlinear-fit"
    - name: Check Rust formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - name: Run Rust code analysis
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all-targets -- -D warnings
    - name: Run Python tests
      run: tox -p -q
    - name: Check Python formatting
      run: black --check --diff .


  arm:

    runs-on: [self-hosted, linux, ARM64]

    steps:
      - uses: actions/checkout@v2
      - name: build all but python
        run: cargo build --workspace --all-targets --exclude python/light-curve
      - name: build python
        run: maturin build
        working-directory: python/light-curve
